name: line lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  line_lint:
    name: line lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: linelint
        uses: fernandrone/linelint@master
